language: php

php:
    - 7.1
    - 7.2
    - 7.3
    - 7.4

before_script:
    - composer install --no-interaction
    - composer dump-autoload -o
    - php -S localhost:9669 server.php &

script:
    - vendor/bin/phpunit --testdox
